# Developed by Tom Evans at Lund University: tom.evans@biol.lu.se
# You are welcome to use parts of this code, but please give credit when using it extensively.
# Code available at https://github.com/thomasevans/lbbg_gps


# A script to analyse each flight, with various
# paramaters, such as maximum altitude, calculated.
# First the database will be queried to pull out
# the data we need for our analysis.
# Second. Various paramaters and information about
# the flights will be calculated.
# Third. This will be ouput to a new database table
# specifically for flights.


# Database functions   ------
# To link to database
library(RODBC)

# Establish a connection to the database
gps.db <- odbcConnectAccess2007('D:/Documents/Work/GPS_DB/GPS_db.accdb')

# See what tables are available
# sqlTables(gps.db)


# Get commuting flights table
flights.com <- sqlQuery(gps.db, query=
                       "SELECT DISTINCT f.*
  FROM lund_flights_commuting_final AS f
  ORDER BY f.flight_id ASC;")






# Get a vector of flight numbers -----
# str(flights.com$flight_id)
flight_id <- sort(flights.com$flight_id)
f <- length(flight_id)


#Run function 'flight.info' in parallel########
require(foreach)
require(doParallel)

#use x cores, general solution for any windows machine.
cl <- makeCluster(parallel::detectCores())     

#start the parellel session of R; the 'slaves', which will run the analysis.
registerDoParallel(cl)   


#this maybe neccessary so that the clustered instances or R have the
#required vairables/ functions in their scope, i.e. those functions
#and vairables which are referred to within the 'foreach' function.
clusterExport(cl, c("flight_id"))   
lst <- list()

system.time({lst <- foreach(i = seq(along = flight_id )) %dopar%{
#  system.time({lst <- foreach(i = c(1:10)) %dopar%{

  source("flight_info.R")
  #calculate the trip numbers for the device i. i.e. the function 
  #which we wish to run for each device.     
#   ans <- lapply(fails, flight.info, type = "com")
#   ans2 <- as.data.frame(ans)
#   warnings()
#   
#   x <-  flight.info(1, type = "com")
#   i <- 5
#   fl <- flight_id[5]
#   is.numeric(fl)
# #   inherits(fl, "int 5")
#   c <- 0
#   while(!is.numeric(fl)  &  c < 5){
#     fl <- flight_id[5]
#     c <- c + 1
#   }
  
  x <- flight.info(flight_id[i], type = "com")
  
  count <- 0
  while((is.na(x[3])) & (count < 5)){
    x <- flight.info(flight_id[i], type = "com")
    count <- count + 1
  }  
  
#   summary(is.na(flight_id))
  
#   flight.info(fails[2], type = "com")
  x <- t(x)

  #output data as list (this will be appended to the global list, lst.
  list(x)   
} #end of foreach functions
}) #end of things being timed by system.time

#close cluster
stopCluster(cl)
#Time taken one time 
#  lst <- mat
# str(mat)

# fail.id <- flight_id[is.na(mat$flight_id)]
# fail.mat <- sapply(fail.id)



#Create dataframe of flights########
#names for the dataframe
names.flights <- c("flight_id",
                   "points", "start_time",
                   "end_time", "duration",
                   "dist_max", "dist_total",
                   "interval_mean", "interval_min",
                   "device_info_serial",
                   "start_long", "start_lat",
                   "end_long", "end_lat",
                   "dist_nest_start",
                   "dist_nest_end",
                   "dist_nest_dif", "dist_a_b",
                   "straigtness", "bearing_a_b",
                   "speed_a_b", "speed_inst_mean",
                   "speed_inst_med",
                   "speed_inst_var", "alt_max",
                   "alt_min", "alt_mean", "alt_med",
                   "rho", "ang_dev", "ang_var")

#make a dataframe from the list generated by the above function.
flights <- data.frame(matrix(unlist(lst), nrow = f, byrow = TRUE))
# data.frame(matrix(unlist(lst), nrow = 3, byrow = T))

row.names(flights) <- NULL

names(flights) <- names.flights

# test <- flights[order(as.numeric(flights$flight_id)),]
# summary(sort(as.numeric(flights$flight_id)) == sort(flight_id))
# 
# sort(as.numeric(flights$flight_id))[1:100]
# str(as.numeric(flights$flight_id))
# sort(sort(flight_id))[1:100]
# str(flight_id)
# # row.names(test) <- NULL
# summary(is.na(flights))
# summary(is.na(test$flight_id))
# flight_id[1:100]
# summary(as.numeric(flights.com$flight_id) == flight_id)
# str(flights)

#origin of UNIX date_time, required for coversion back to datetime objects for start_time and end_time
startdate <- "1970-01-01"
startdate <- as.Date(startdate)

#convert the end_time back to datetime format
flights$end_time <- as.POSIXct(
  as.POSIXlt(flights$end_time, origin=startdate,
             tz= "GMT",format="%Y-%m-%d %H:%M:%S"))

#conver the start_time back to datetime format
flights$start_time <- as.POSIXct(
  as.POSIXlt(flights$start_time, origin=startdate,
             tz= "GMT",format="%Y-%m-%d %H:%M:%S"))

# save(flights, file = "flights_part1.Rdata")


fx <- function(x){
  x <- as.character(x)
  as.numeric(x)
}

flights2 <- cbind(sapply(flights[,c(1,2)], fx), flights[,c(3,4)],sapply(flights[,5:31], fx))

# warnings()

# str(flights2)


  

  idx   <- c(1:length(flight_id))
  idx[is.na(flights2$flight_id)]
  fails <- (flight_id[is.na(flights2$flight_id)])
  fails
  load("fails1.RData")
  all.equal(fails,fails_1)
#   fails %in% fails_1
  test.in <- function(x, x2){
    x %in% x2
  }
  sapply(fails, test.in, x2 = fails_1)

#   flights2[1317,]



  flights4 <- flights2[order((flights.com$flight_id)),]
  fails <- (flight_id[is.na(flights4$flight_id)])

 flights3 <- flights2[!is.na(flights2$flight_id),]
  all.equal(flights3$flight_id, flight_id[!is.na(flights4$flight_id)])



#output data to database##################

#export flight information to the database
#will be neccessary to edit table in Access after to define data-types and primary keys and provide descriptions for each variable.
sqlSave(
  gps.db, flights3, tablename = "lund_flights_commuting_par",
  append = FALSE, rownames = FALSE,
  colnames = FALSE, verbose = FALSE,
  safer = TRUE, addPK = FALSE,
  fast = TRUE, test = FALSE,
  nastring = NULL,
  varTypes = c(start_time = "Date", end_time= "Date"))
  
message("After exporting table to DB, edit table in Access to define data-types and primary keys")




fails_1 <- fails
  save(fails_1, file = "fails1.RData")

