# Script to parse csv files generated by GPSBabbel from
# conversion of @trip files

# Set working directory to location of files:
setwd("D:/Dropbox/Guillemots/guillemot_2009_data/csv_from_gpx")

# Import all files
AAK959_g1 <- read.csv("AAK959_g1_2009_06_16.gpx.csv")
AAK960_g2 <- read.csv("AAK960_g2_09_06_12.gpx.csv")
AAK961_g5 <- read.csv("AAK961_g5_09_06_20.gpx.csv")
AAK962_g3 <- read.csv("AAK962_g3_09_06_13.gpx.csv")
AAK963_g4 <- read.csv("AAK963_g4_09_06_14.gpx.csv")
AAK966_g3 <- read.csv("AAK966_g3_2009_06_19.gpx.csv")

# For each add columns with device_info_serial, and ring_number
AAK959_g1 <- cbind(AAK959_g1,"AAK959","gx1")
AAK960_g2 <- cbind(AAK960_g2,"AAK960","gx2")
AAK961_g5 <- cbind(AAK961_g5,"AAK961","gx5")
AAK962_g3 <- cbind(AAK962_g3,"AAK962","gx3")
AAK963_g4 <- cbind(AAK963_g4,"AAK963","gx4")
AAK966_g3 <- cbind(AAK966_g3,"AAK966","gx3")

name.vector <- c(names(AAK959_g1)[1:7],
                      "ring_number",
                      "device_info_serial")

names(AAK959_g1) <- name.vector
names(AAK960_g2) <- name.vector
names(AAK961_g5) <- name.vector
names(AAK962_g3) <- name.vector
names(AAK963_g4) <- name.vector
names(AAK966_g3) <- name.vector


# Combine all into a single dataframe
all.points <- rbind(AAK959_g1,
                    AAK960_g2,
                    AAK961_g5,
                    AAK962_g3,
                    AAK963_g4,
                    AAK966_g3)

# Drop first column
all.points <- all.points[,2:9]

names(all.points)

# Date_time
# combine date and time into a character vector
date_time <- paste(all.points$Date, all.points$Time, sep = " ")
# Convert to date-time object
date_time <-  as.POSIXct(strptime(date_time,
                          format = "%Y/%m/%d %H:%M:%S",
                          tz = "UTC"))

# Convert from km/h to ms-1
speed_ms <- (all.points$Speed * 1000)/(60*60)

# hist(speed_ms, ylim = c(0,1000))

# Combine together to new data-frame following format of
# 2014 data
all.points.exp <- cbind(all.points$device_info_serial,
                        date_time,
                        all.points$Latitude,
                        all.points$Longitude,
                        all.points$Altitude,
                        speed_ms,
                        all.points$ring_number                        
                        )

all.points.exp <- as.data.frame(all.points.exp)

names(all.points.exp) <- c("device_info_serial",
                           "date_time",
                           "latitude",
                           "longitude",
                           "elev",
                           )





